# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLRedirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=4096)),
                ('unique_code', models.CharField(blank=True, max_length=8, unique=True)),
            ],
        ),
    ]
